# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-19 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0002_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.CharField(max_length=120, verbose_name='Icon'),
        ),
    ]
