# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-19 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0003_auto_20160619_0421'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha Inicio')),
                ('fecha_termino', models.DateField(verbose_name='Fecha Termino')),
            ],
            options={
                'verbose_name': 'Experiencia',
                'verbose_name_plural': 'Experiencias',
            },
        ),
    ]
