# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-19 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0004_experiencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencia',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
