# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-01 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0005_experiencia_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('posicion', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('image', models.ImageField(upload_to='proyecto', verbose_name='Imagen')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria_proyecto', to='portafolio.Categoria')),
            ],
            options={
                'verbose_name': 'proyectos',
                'verbose_name_plural': 'proyectoss',
            },
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cv',
            field=models.FileField(upload_to='', verbose_name='PDF'),
        ),
    ]
