# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-29 22:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0006_categoria_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='categoria',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='categoria_proyecto', to='portafolio.Categoria'),
            preserve_default=False,
        ),
    ]
