# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-01 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0006_auto_20160701_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='cv',
            field=models.FileField(upload_to='cv', verbose_name='PDF'),
        ),
    ]
