# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-08 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0007_proyecto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='posicion',
            field=models.PositiveIntegerField(default=0, verbose_name='Posicion'),
        ),
    ]
