# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-08 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0009_auto_20160708_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='posicion',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
