# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-08 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0010_proyecto_posicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='url',
            field=models.URLField(blank=True, verbose_name='Url'),
        ),
    ]
