# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-05 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0011_proyecto_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencia',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='Logo'),
        ),
    ]
