# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-05 19:52
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0012_experiencia_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencia',
            name='logo',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='logo'),
        ),
    ]
