# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-17 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0014_estudios_carrera'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='tipo',
            field=models.CharField(choices=[(b'', b'----'), (b'Frontend', b'FR'), (b'Backend', b'BC')], default='', max_length=120, verbose_name='Tipo'),
            preserve_default=False,
        ),
    ]
