# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-17 01:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0015_skill_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('posicion', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'TipoSkill',
                'verbose_name_plural': 'TipoSkills',
            },
        ),
        migrations.RemoveField(
            model_name='skill',
            name='tipo',
        ),
        migrations.AddField(
            model_name='skill',
            name='tipo_skill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_skill_set', to='portafolio.TipoSkill'),
        ),
    ]
