# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-19 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0016_auto_20161116_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='descripcion',
            field=models.CharField(default='', max_length=255, verbose_name='Descripcion'),
            preserve_default=False,
        ),
    ]
