# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-19 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0017_proyecto_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('posicion', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Tags',
                'verbose_name_plural': 'Tagss',
            },
        ),
        migrations.AddField(
            model_name='proyecto',
            name='tags',
            field=models.ManyToManyField(null=True, related_name='tags_set', to='portafolio.Tags'),
        ),
    ]
